---

- name: Install EPEL repo.
  become: true
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Import EPEL GPG key.
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present

- name: Install docker dependencies
  package: name="{{ item }}" state=latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: true
  tags:
    - skip_ansible_lint

- name: Add repository
  become: true
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  package: name="docker-ce-{{ docker_ce_version }}.ce" state="present"
  become: true

- name: Start docker
  become: true
  service:
    name: "docker"
    state: started
    enabled: true

- name: Create allow containers communication service
  copy:
    src: "allow_containers_communication.service"
    dest: "/etc/systemd/system/allow_containers_communication.service"
  become: true
  when: docker_allow_containers_communication

- name: Launch allow containers communication service
  systemd:
    name: allow_containers_communication.service
    state: started
    enabled: true
  become: true
  when: docker_allow_containers_communication

- name: Install pip
  package:
    name: "python-pip"
    state: latest
  become: true
  tags:
    - skip_ansible_lint

- name: Install docker python module
  become: true
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
